project:
  type: website
  resources:
    - "my-name.m4a"
    - "post/slidecraft-layout/_*.qmd"
    - "post/slidecraft-layout/_*.html"

execute:
  freeze: true
  keep-md: true

website:
  site-url: "https://emilhvitfeldt.com/"
  description: "Emil Hvitfeldt blog about R, slides and modeling"

  favicon: logo.png
  open-graph: true
  navbar:
    left:
      - text: "Home"
        href: index.qmd
    right:
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Talks"
        href: talks.qmd
      - icon: github
        href: https://github.com/emilhvitfeldt
      - icon: rss
        href: blog.xml

format:
  html:
    toc: true
    theme:
      - styles.scss
    grid:
      body-width: 840px
    html-math-method: plain